<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buy groceries_edit-todo-input</name>
   <tag></tag>
   <elementGuidId>6bf887e1-1ec5-4345-948d-08a6b1bd0e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-todo-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-todo-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Edit Todo Input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b369688d-e150-4c93-9e5d-ed64e9330e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-todo-input</value>
      <webElementGuid>06465b34-2958-450d-bb71-11b30dead9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>735c3e64-9a06-4d82-9cea-6d97874410c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>3b2d4002-36fb-41f9-9669-731f557b94c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-todo-input&quot;)</value>
      <webElementGuid>289cda55-48da-4354-81c0-540c2bbe3f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-todo-input']</value>
      <webElementGuid>5d499915-7807-4f0d-b585-1c95e1ec1377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1b77b000-0171-4732-a398-acce896e2dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edit-todo-input' and @type = 'text']</value>
      <webElementGuid>0b5acbcf-7ab2-43cb-bd9f-b0a0f116f678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
