<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todo_item--label</name>
   <tag></tag>
   <elementGuidId>953b2a77-9726-4889-a2b7-813ec28e0292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/section/main/ul/li/div[contains(@class, 'view')]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>59c0ac9c-be23-441e-a2e7-b4c684b09b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1739214539258</value>
      <webElementGuid>ba90eb45-fd56-4359-952e-1b4fac497439</webElementGuid>
   </webElementProperties>
</WebElementEntity>
