<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todo_item--edit</name>
   <tag></tag>
   <elementGuidId>7209eaae-f6ca-4305-a394-033f4e6b47d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'edit-todo-input' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.editing > div.input-container > #edit-todo-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='edit-todo-input'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3b73647-46d7-46c0-99d0-f3de75605a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-todo-input</value>
      <webElementGuid>a4fed47a-1405-432e-8dff-107acfea04a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ac6ce3d-73e1-4cbf-b5ea-253d658a689c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>9e83d560-efb8-480d-b89d-8e316d6fb0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;todoapp&quot;]/main[@class=&quot;main&quot;]/ul[@class=&quot;todo-list&quot;]/li[@class=&quot;editing&quot;]/div[@class=&quot;input-container&quot;]/input[@id=&quot;edit-todo-input&quot;]</value>
      <webElementGuid>27f18e1e-447d-4674-972e-f61e02c98cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='edit-todo-input'])</value>
      <webElementGuid>67b5b92b-e50a-483f-9adc-4732dcde961e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a2cda1d4-ce61-4c92-bafd-381e4b9a0e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'edit-todo-input' and @type = 'text']</value>
      <webElementGuid>5ce743c3-2670-4c54-985f-cbab4e1b562d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
