<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filter--all</name>
   <tag></tag>
   <elementGuidId>360e6d4b-d364-44f5-a937-5be8bcf50e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.router-link-active.router-link-exact-active.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'All')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;All&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08947c28-e35e-4aca-b365-9cc3a1c6a5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/</value>
      <webElementGuid>36c9a8e9-1630-4377-9eee-a383806d859b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>router-link-active router-link-exact-active selected</value>
      <webElementGuid>d2258467-006e-4cfc-ac01-9d77a8fcecbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>e6a981b4-5929-415d-a138-b133a22a7522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>1e111c8f-f73b-4f28-9860-68d2163a2397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;todoapp&quot;]/footer[@class=&quot;footer&quot;]/ul[@class=&quot;filters&quot;]/li[1]/a[@class=&quot;router-link-active router-link-exact-active selected&quot;]</value>
      <webElementGuid>09979d95-7e29-4b41-a868-94f1316ba3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All')]</value>
      <webElementGuid>24addf72-813b-4eb2-85ef-e353afcfed60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Todo Input'])[3]/following::a[1]</value>
      <webElementGuid>5e136c4c-0edf-4092-9d89-5729620c372d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[1]</value>
      <webElementGuid>ce217a58-d8e0-489a-ac58-34226855a975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[1]/preceding::a[2]</value>
      <webElementGuid>dc1629e8-fa77-4082-8b6d-7b7939478074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>34600df5-70ae-4490-a22e-59aa74978f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/')])[2]</value>
      <webElementGuid>0628fa7a-5c03-41e3-adaf-3970c8848b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>f6bd6b29-2e15-40e6-98e3-c2fdda97ee0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>b9dfc068-4d00-466d-a8c6-22e11bcbaf75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
