<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footer--txt_items-left</name>
   <tag></tag>
   <elementGuidId>89ee91a3-78bd-422b-965a-f96aad108856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.filters</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Todo Input'])[3]/following::ul[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AllActiveCompleted&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>3f012b66-922b-4e3c-9e1b-cf90b3c3dd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/footer/span/strong</value>
      <webElementGuid>ab6ec476-2471-410c-8a5d-c463e2cae147</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Todo Input'])[3]/following::ul[1]</value>
      <webElementGuid>97878d26-ae79-45d5-8edb-d657a030dd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/ul</value>
      <webElementGuid>ea856ffa-8770-46f1-8e94-7d6ef8b5ddec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'AllActiveCompleted' or . = 'AllActiveCompleted')]</value>
      <webElementGuid>e1d022d4-991d-498d-b591-7752600694ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
