<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>todo_item--btn_destroy</name>
   <tag></tag>
   <elementGuidId>59df2d59-ef8c-47e6-b4b4-45f1c5c06be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.destroy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bb43d89-4f87-4f59-bbee-de8c82eacf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>destroy</value>
      <webElementGuid>0cd4b39c-c4a3-4a7f-b0dd-4daea72f9c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;todoapp&quot;]/main[@class=&quot;main&quot;]/ul[@class=&quot;todo-list&quot;]/li[@class=&quot;completed&quot;]/div[@class=&quot;view&quot;]/button[@class=&quot;destroy&quot;]</value>
      <webElementGuid>d689f113-70dc-4ce4-a80d-288bd3d63cbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c20a65ba-5ec2-47e8-a249-2bdcac188b92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
